### ISSUE TITLE
No keep alive yet 

### ISSUE THREAD

**Issue by glutamatt** [glutamatt/glutaslacker#1]
So the service hosted on heroku fall asleep.

To-do : set http call to the service to keep the app running. Possibly during a determined time-frame, because of the 6 hours sleep time required by free heroku instances

**Comment by glutamatt** [comment]
@genesor you would be so kind :kissing_closed_eyes: 
I will give you administration rights on the heroku app!

**Comment by genesor** [comment]
I'll add a something to keep the dyno alive. I'm also gonna search something to allow some timespan when the dyno is allowed to sleep.

**Comment by glutamatt** [comment]
i tried a first version : https://github.com/glutamatt/glutaslacker/commit/02efc7392f714907506c0c96ab973f2a249b01c9

but nothing can wake the instance up in the morning
